# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s=s.split()
s

['Hi', 'there', 'Sam!']

2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of",planet,"is",diameter,"kilometers")

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
a=d["k1"]
b=a[3]
c=b["tricky"]
aa=c[3]
aaa=aa["target"]
aaa=aaa[3]
aaa

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array=np.arange(20,35,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a, b), axis=0)
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
exam_data  = {'name': ['Anastasia', 'Dima'],'score': [12.5, 9],'attempts': [1, 3]}

In [ ]:
df = pd.DataFrame(exam_data)
print(df)

        name  score  attempts
0  Anastasia   12.5         1
1       Dima    9.0         3


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
K = 41
date_generated = pd.date_range(test_date, periods=K)
exam_date={"date":date_generated.strftime("%d-%m-%Y")}
df = pd.DataFrame(exam_date)
print(df)

          date
0   01-01-2023
1   02-01-2023
2   03-01-2023
3   04-01-2023
4   05-01-2023
5   06-01-2023
6   07-01-2023
7   08-01-2023
8   09-01-2023
9   10-01-2023
10  11-01-2023
11  12-01-2023
12  13-01-2023
13  14-01-2023
14  15-01-2023
15  16-01-2023
16  17-01-2023
17  18-01-2023
18  19-01-2023
19  20-01-2023
20  21-01-2023
21  22-01-2023
22  23-01-2023
23  24-01-2023
24  25-01-2023
25  26-01-2023
26  27-01-2023
27  28-01-2023
28  29-01-2023
29  30-01-2023
30  31-01-2023
31  01-02-2023
32  02-02-2023
33  03-02-2023
34  04-02-2023
35  05-02-2023
36  06-02-2023
37  07-02-2023
38  08-02-2023
39  09-02-2023
40  10-02-2023


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists, columns =['num', 'name','age']) 
print(df )

   num name  age
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
